# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deployment.yaml

images:
  - name: gcr.io/nutrien-exercise/nutrien-artifacts-repo/nutrien-gke
    newName: gcr.io/nutrien-exercise/nutrien-artifacts-repo/nutrien-gke
    newTag: ${TAG}